### ISSUE TITLE
SDG for palett model

### ISSUE THREAD

**Issue by hwulfmeyer** [NVIDIA-Omniverse/synthetic-data-examples#8]
Repository contains the deep learning model for the synthetic pallets but not how the synthetic data was generated.
Please include.
@dennis-lynch-nv

**Comment by dennis-lynch-nv** [comment]
See the blog post here: https://developer.nvidia.com/blog/how-to-train-autonomous-mobile-robots-to-detect-warehouse-pallet-jacks-using-synthetic-data/

I can work on extracting the code from the blog to the repository

**Comment by dennis-lynch-nv** [comment]
https://github.com/NVIDIA-Omniverse/synthetic-data-examples/tree/main/end-to-end-workflows/palletjack_with_tao/palletjack_sdg
